### ISSUE TITLE
Create mockup

### ISSUE THREAD

**Issue by nya-elimu** [elimu-ai/battery#1]

**Comment by jo-elimu** [comment]
@adrygll2 Inspiration:

![charge_galaxy_s7_battery_wall_charger](https://cloud.githubusercontent.com/assets/1451036/19849004/c648f080-9f61-11e6-9bc3-fa0acf3bf19e.gif)

![solarcharger_01](https://cloud.githubusercontent.com/assets/1451036/19849049/033ac0cc-9f62-11e6-8c69-6824f2de14d3.gif)

**Comment by jo-elimu** [comment]
@adrygll2 If you need it, I could also record a video of plugging the cable into a Pixel C device (to make it more relevant).

**Comment by adrygll2** [comment]
@jogrimst I will search Gifs with Pixel C, also I think I could make one by my own with some images. The video It's a good idea too.

**Comment by jo-elimu** [comment]
> @jogrimst I will search Gifs with Pixel C, also I think I could make one by my own with some images. The video It's a good idea too.

@adrygll2 Ok. Also, we can also easily convert a video to GIF if needed.
