### ISSUE TITLE
Create receiver for handling changes in battery state

### ISSUE THREAD

**Issue by nya-elimu** [elimu-ai/battery#5]

**Comment by jo-elimu** [comment]
@adrygll2 See https://developer.android.com/training/monitoring-device-state/battery-monitoring.html

**Comment by adrygll2** [comment]
@jogrimst The app be always on from the start isn't it?, Because we need check the battery status all time the device is activated.

**Comment by jo-elimu** [comment]
> The app be always on from the start isn't it?, Because we need check the battery status all time the device is activated.

@adrygll2 If this can be solved using a receiver, no background service is necessary. But if the Android system rarely broadcasts intents with information about the battery state, it might be necessary to create a background service for continuously checking the battery level.

**Comment by jo-elimu** [comment]
@adrygll2 Can we detect when the battery level reaches 10%?
